-- Generated by scripts/import/build-import-sql.mjs — do not edit by hand.
-- Source: src/data/seed/catalogo-limpio.csv, src/data/seed/contactos-limpio.csv
--
-- Idempotent: safe to run repeatedly. Never writes price_per_day or
-- total_quantity, and never overwrites a name or label staff have overridden.
--
-- Products:  103
-- Variants:  129
-- Customers: 159
-- Skipped:   5 rows (see EXCLUDED in the build script)

-- ---- Categories ------------------------------------------------------
-- Top-level first, then subcategories, which resolve their parent by slug.

insert into categories (slug, name, parent_id, display_order)
select v.slug::text, v.name::text, null, v.display_order::int
from (values
  ('sillas', 'Sillas', 0),
  ('mesas', 'Mesas', 1),
  ('manteleria', 'Mantelería', 2),
  ('cristaleria', 'Cristalería', 3),
  ('decoracion', 'Decoración', 4),
  ('caballo-bayo', 'Caballo Bayo', 5),
  ('utensilios', 'Utensilios', 6)
) as v(slug, name, display_order)
on conflict (slug) do update set
  name = excluded.name,
  parent_id = excluded.parent_id,
  display_order = excluded.display_order;

insert into categories (slug, name, parent_id, display_order)
select v.slug::text, v.name::text, p.id, v.display_order::int
from (values
  ('cristaleria-copas', 'Copas', 'cristaleria', 0),
  ('cristaleria-cubiertos', 'Cubiertos', 'cristaleria', 1),
  ('cristaleria-platos', 'Platos', 'cristaleria', 2),
  ('cristaleria-vasos', 'Vasos', 'cristaleria', 3),
  ('manteleria-lazos', 'Lazos', 'manteleria', 4),
  ('manteleria-manteles', 'Manteles', 'manteleria', 5),
  ('manteleria-otros', 'Otros', 'manteleria', 6)
) as v(slug, name, parent_slug, display_order)
join categories p on p.slug = v.parent_slug::text
on conflict (slug) do update set
  name = excluded.name,
  parent_id = excluded.parent_id,
  display_order = excluded.display_order;
